apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: euforicio-app
    releaseName: euforicio-app
    version: 0.1.39
    repo: https://euforicio.github.io/helm-charts
    valuesInline:
      name: ${{values.component_id}}
      image:
        repository: ghcr.io/euforicio/${{values.component_id}}
        tag: latest
      autoscaling:
        enabled: ${{values.autoscaling}}
        minReplicas: ${{values.minReplicas}}
        maxReplicas: ${{values.maxReplicas}}
        targetCPUUtilizationPercentage: ${{values.targetCPUUtilizationPercentage}}
      resources:
        requests:
          memory: ${{values.requests_memory}}
          cpu: ${{values.requests_cpu}}
        limits:
          memory: ${{values.limits_memory}}
          cpu: ${{values.limits_cpu}}
